version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "2052:80/tcp"
      - "2053:443/tcp"
    environment:
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ${CONFIG}:/etc/pihole
      - ${DNSMASQ}:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
